server:
  profiles:
    active: default

  port: 9000

spring:
  application:
    name: free-social-gateway

  datasource:
    url: jdbc:postgresql://localhost:5432/freesocial?useSSL=false
    username: postgres
    password: "root"
    driver-class-name: org.postgresql.Driver
    connection-timeout: 20000
    max-pool-size: 250
    idle-timeout: 300000
    minIdle: 5

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://raspberryge:8085/eureka
  instance:
    lease-renewal-interval-in-seconds: 5