server:
  profiles:
    active: default

  port: 8085

spring:
  application:
    name: free-social-service-discovery

eureka:
  renewalPercentThreshold: 0.85
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://raspberryge:8085/eureka