server:
  profiles:
    active: default

  port: 8084

spring:
  application:
    name: free-social-service-discovery

  datasource:
    url: jdbc:postgresql://localhost:5432/freesocial?useSSL=false
    username: postgres
    password: "root"
    driver-class-name: org.postgresql.Driver
    connection-timeout: 20000
    max-pool-size: 250
    idle-timeout: 300000
    minIdle: 5