server:
  profiles:
    active: default

  port: 8083

spring:
  application:
    name: free-social-posts

  jpa:
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:5432/freesocial?useSSL=false
    username: postgres
    password: "root"
    driver-class-name: org.postgresql.Driver
    connection-timeout: 20000
    max-pool-size: 250
    idle-timeout: 300000
    minIdle: 5

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8085/eureka

freesocial:
  posts:
    filesdir: "D:/freesocial/posts/files/%s.%s"