server:
  profiles:
    active: default

  port: 8082

  error:
    include-message: always

spring:
  application:
    name: free-social-token-jobs

  jpa:
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:5432/freesocial?useSSL=false
    username: postgres
    password: "root"
    driver-class-name: org.postgresql.Driver
    connection-timeout: 20000
    max-pool-size: 250
    idle-timeout: 300000
    minIdle: 5